election/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import views as auth_views
from voting import views as reg_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("voting.urls")),
    path('', include("authusers.urls")),
    path('login/', auth_views.login, {'template_name': 'voting/login.html'}, name='login'),
    path('logout/', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^signup/$', reg_views.signup, name='signup'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^account_activation_sent/$', reg_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        reg_views.activate, name='activate'),
    # password change url definitions
    url(r'^accounts/password/change/$', auth_views.password_change, {
        'template_name': 'registration/password_change_form.html'},
        name='password_change'),
    url(r'^accounts/password/change/done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_done.html'},
        name='password_change_done'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "users"
urlpatterns = [
    path('home', views.home, name='home'),
    path('dashboard', views.home, name='dashboard'),
 ]

voting/urls.py
from django.urls import path

from django.conf.urls import url
from voting import views as reg_views

from . import views

app_name = "voting"
urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    #path('signup', views.signup, name='signup'),
    #path('login', views.login, name='login'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    url(r'^update_profile', views.update_profile, name='update_profile'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        reg_views.activate, name='activate'),
]

voting/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# class User(models.Model):
#     idUser = models.AutoField( primary_key=True)
#     firstName = models.CharField(max_length=200)
#     secondName = models.CharField(max_length=200)
#     userType = models.CharField(max_length=200)
#     email = models.CharField(max_length=200)
#     creationDate = models.DateTimeField('date published') 

class Elections(models.Model):
    idElection = models.AutoField(primary_key=True)
    User_idUser = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    voterType = models.CharField(max_length=200)
    electorType = models.CharField(max_length= 200)

    def __str__(self):
        return self.name
# class Login(models.Model):
#     idLogin = models.AutoField(primary_key=True)
#     email = models.CharField(max_length= 200)
#     matricule = models.CharField(max_length=200)
#     password = models.CharField(max_length=200)
#     state = models.CharField(max_length= 200)
#     activationLink = models.CharField(max_length = 200)
 #   User_idUser = models.ForeignKey(User, on_delete=models.CASCADE)

#the different positions in the Election
class Position(models.Model):
    idPosition = models.AutoField(primary_key= True)
    name = models.CharField(max_length = 100)
    election = models.ForeignKey(Elections, on_delete=models.CASCADE, default=1)

#get the candidates of an election
class Candidate(models.Model):
    idCandidate = models.AutoField(primary_key=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, default=1)
    election = models.ForeignKey(Elections, on_delete=models.CASCADE, default=1)
    userid = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    user = models.CharField(max_length= 100, default='Nges')

class Voting(models.Model):
    idVoting = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, default=1)
    election = models.ForeignKey(Elections, on_delete=models.CASCADE, default=1)

#contact us details 
class Contact(models.Model):
    idContact = models.AutoField(primary_key=True)
    topic = models.CharField(max_length= 200)
    body = models.CharField(max_length= 500)
    email = models.CharField(max_length= 80)

#To define the various post availble with the election


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    # other fields...

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

def set_email_as_unique():
    """
    Sets the email field as unique=True in auth.User Model
    """
    email_field = dict([(field.name, field) for field in User._meta.fields])["email"]
    setattr(email_field, '_unique', True)

#this is called here so that attribute can be set at the application load time
set_email_as_unique()

#To upload documents
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

voting/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Contact

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UpdateProfile(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
        return email

    def save(self, commit=True):
        user = super(UpdateProfile, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class ContactForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Contact
        fields = ('topic', 'email', 'body')
        #save 
    def save(self, commit=True):
        contact = super(ContactForm, self).save(commit=False)
        if commit:
            contact.save()
        return contact

voting/views.py
from django.http import HttpResponse

from django.shortcuts import render, redirect

from voting.forms import SignUpForm, UpdateProfile

from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes

from django.utils.http import urlsafe_base64_encode

from django.template.loader import render_to_string

from voting.tokens import account_activation_token

from django.contrib.auth import login

from django.contrib.auth.models import User

from django.utils.encoding import force_text

from django.utils.http import urlsafe_base64_decode

from .forms import ContactForm

def index(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'voting/index.html')

def about(request):
    return render(request, 'voting/about.html')

def contact(request):
    args = {}
    if request.method == 'POST':    #form submitted
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            #display and alert upon successful sav
            msgInfo = "Your Feedback has been submitted!"
            args['msgInfo'] = msgInfo
            #return redirect('guest:update_profile_success')
    form = ContactForm()

    args['form'] = form
    return render(request, 'voting/contact.html', args)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your EVS Account'
            message = render_to_string('voting/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'voting/signup.html', {'form': form})

def account_activation_sent(request):
    return render(request, 'voting/account_activation_sent.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('authusers:home')
    else:
        return render(request, 'voting/account_activation_invalid.html')

def update_profile(request):
    args = {}
    if request.method == 'POST':    #form submitted
        form = UpdateProfile(request.POST, instance=request.user)
        #form.actual_user = request.user
        if form.is_valid():
            form.save()
            #display and alert upon successful sav
            msgInfo = "Your profile info successfully updated!"
            args['msgInfo'] = msgInfo

    user = request.user
    form = UpdateProfile(initial={'email': user.email, 'username': user.username, 'first_name': user.first_name, 'last_name': user.last_name})

    args['form'] = form
    return render(request, 'voting/update_profile.html', args)

voting/templates/voting/about.html
{% extends 'voting/main.html' %}

{% block title %}About  Panther Es{% endblock %}

{% block content %}
ABOUT
{% endblock %}

voting/templates/voting/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'voting:activate' uidb64=uid token=token %}
{% endautoescape %}

voting/templates/voting/account_activation_invalid.html
{% extends 'siteLayout.html' %}

{% block title %}Account activation link is invalid{% endblock %}

{% block content %}
    <br />
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
                <div class="panel panel-site" style="border-top: none; border-right: none">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                <h1 class="fg-site"><b>Account activation link is invalid</b></h1>
                                  <p class="lead text-danger">
                                    Your account activation link is invalid or has expired!!
                                  </p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
{% endblock %}

voting/templates/voting/account_activation_sent.html
{% extends 'siteLayout.html' %}

{% block title %}Account activation link sent to your mail box{% endblock %}

{% block content %}
    <br />
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
                <div class="panel panel-site" style="border-top: none; border-right: none">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                <h1 class="fg-site"><b>Account activation link sent to your mail box</b></h1>
                                  <p class="lead">
                                    An account activation link has been sent to your mail box. If you entered a valid and existing email,
                                    You should receive it shortly.
                                  </p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
{% endblock %}

voting/templates/voting/contact.html
{% extends 'voting/main.html' %}

{% block title %}Contact{% endblock %}

{% block content %}

<h1>Contact us</h1>

{% if msgInfo %}
	<div class="alert alert-info">
		{{ msgInfo }}
	</div>
{% endif %}
<br><br>
<form method="POST" novalidate class="form-group form-control col-md-6" style="margin-left: 23%">
	Contact Us<hr>
	<table>
	{% csrf_token %}
	{{ form.as_table }}
	</table>
	<p><input type="submit" class="btn btn-secondary" value="Submit"></p>
</form>

{% endblock content %}

voting/templates/voting/index.html
{% extends 'voting/main.html' %}

{% block title %}Welcome to  Panther Es{% endblock %}

{% block content %}

    <br />
    <div>
          <div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://arynews.tv/en/wp-content/uploads/2018/04/vote1.jpg" alt="Los Angeles">
    </div>
    <div class="carousel-item">
      <img src="https://s-i.huffpost.com/gen/1443494/images/o-WHITE-PEOPLE-BUSINESS-SUITS-facebook.jpg" alt="Chicago">
    </div>
    <div class="carousel-item">
      <img src="http://www.urdunews.com/sites/default/files/2018/04/19/292996-1939184536.jpg" alt="New York">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>
        </div>
    <div class="row">
        <div class="container">
                <div class="panel panel-site" style="border-top: none; border-right: none">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-12 text-center text-secondary"><br>
                                <h2 class="fg-site"><b>Welcome to Panther Electoral System</b></h2>
                                  <p class="lead text-center">
                                     The Home For Elections
                                  </p>
                            </div>
                             
                        </div>
                    </div>
                </div>
                     <div class="container text-center ">
                            <div class="row">
                                     <div class="card col-md-4" style="width:400px">
                                            <img class="card-img-top" src="http://www.personal.kent.edu/~lzucca/j0433151.jpg" style="width:100%">
                                            <div class="card-body">
                                              <h4 class="card-title">John Electorial</h4>
                                              <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                                              <a href="#" class="btn btn-secondary">View this contest</a>
                                            </div>
                                          </div>
                                          <div class="card  col-md-4" style="width:400px">
                                            <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSet81BrzDA5rrpzQSv9QtekNOQjG2dpM-ySyZCX1iHI1QoYx8h"style="width:100%">
                                            <div class="card-body">
                                              <h4 class="card-title">Final year Contest</h4>
                                              <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                                              <a href="#" class="btn btn-secondary">View this contest</a>
                                            </div>
                                          </div>
                                          <div class="card  col-md-4" style="width:400px">
                                            <img class="card-img-top" src="https://pa1.narvii.com/6448/7b56bce6fd36bbe472706af320429950a80b457f_hq.gif"style="width:100%; height: 43%">
                                            <div class="card-body">
                                              <h4 class="card-title">School Star</h4>
                                              <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
                                              <a href="#" class="btn btn-secondary">View this contest</a>
                                            </div>
                                          </div>
                                    </div><br><br>
                                    <div class="row form-group" style="margin-left: 33%;"><span>Email: </span><input class=" off-set-md-2 form-control col-md-5" type="email" name="email" placeholder="Please subcribe to our news"><input type="Submit" name="subscribe" class="btn btn-info"></div>
                            </div>
                    </div>
    </div>
{% endblock %}

voting/templates/voting/login.html
{% extends 'voting/main.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row image">
            <form method="post" style="margin-top: 15%; margin-left: 35%; margin-bottom: 10%">
                <div class="form-control">
                 <div style="margin-left: 3%">
                    <div class="">
                        <div class="row">
                            <div class=" ">
                                <h1 class="form-group"><b>Login to Panther ES</b></h1><hr>
                                {% csrf_token %}
                               {{ form.as_p }}
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="">
                                <button class="btn btn-secondary" type="submit"><b>Login</b></button><br>
                                 Don't have an account yet?
                                <a href="{% url 'signup' %}"><b>signup</b></a>
                                <br />Forgot password?
                                <a href="{% url 'password_reset' %}"><b>Reset password</b></a>
                            </div>
                        </div>
                    </div>
                 </div>
                </div>
            </form>
        <div><br><br><br>











    <!--div class="row">
        <div class="text-center">
            <form method="post">
                <div class="" style="border-top: none; border-right: none">
                    <div class="">
                        <div class="row">
                            <div class="col-sm-10 ">
                                <h1 class="form-group"><b>Login to Panther ES</b></h1>
                                {% csrf_token %}
                               {{ form.as_p }}
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1 clearfix">
                                Don't have an account yet?
                                <a href="{% url 'signup' %}"><b>signup</b></a>
                                <button class="btn btn-secondary pull-right" type="submit"><b>Login</b></button>
                                <br />Forgot password?
                                <a href="{% url 'password_reset' %}"><b>Reset password</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div-->
{% endblock content %}

voting/templates/voting/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Panther - Electoral System{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/site.css' %}">
        
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
         <style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width: 100%;
      height: 100%;
  }
  </style>
    </head>
      <body>

        <nav class="navbar navbar-inverse navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand" href="#">Panther - Electoral System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class= "collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto nav navbar-right">
                <li class="active nav-item">
                  <a class="nav-link" href="{% url 'voting:index' %}">Home</a></li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">
                    <span class="">
                    </span> Login
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}"><span></span> Sign Up
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'voting:about' %}">
                    <span></span> About
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'voting:contact' %}">
                    <span class="glyphicon glyphicon-envelope"></span> Contact
                 </a>
               </li>
              </ul>
            </div>
          </div>
        </nav>

         <div class="">
              {% block content %}Empty page!{% endblock content %}
          </div>

          <!--div class="footer container-fluid ">
                          <div class="col-sm-2">
                              <div class="pull-left" id="google_translate_element"></div>
                              <!--script type="text/javascript">
                                  function googleTranslateElementInit() {
                                    new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'fr,en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false}, 'google_translate_element');
                                  }
                              </script-->
                              <!--script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script-->
                          <!--/div>
                          <div class="col-sm-6 ">
                              <p class="text-center lead">
                                  <a class="fg-site" href="#" title="Online voting system">
                                      <span>&copy; PES 2018</span>
                                  </a> ||
                                  <a class="fg-site" href="about" title="About us">About</a> ||
                                  <a class="fg-site" href="contact" title="Contact us">Contact</a> ||
                                  <a class="fg-site" href="signup" title="About us">Signup</a> ||
                                  <a class="fg-site" href="login" title="Contact us">Login</a> ||
                              </p>
                          </div>
                          <div class="col-sm-4">
                              <p class="lead pull-right">
                                  Powered by <span class="fg-site">Tech Panther </span>
                              </p>
                          </div>
          </div-->
          <br><br><br>
          <footer class="footer bg-dark" style="position: relative;">
            <div class="container-fluid">
              <span class="text-basic">Powered by Mondjo Perside & Nges Brian</span>
            </footer>
          </div>
      </body>
       
</html>

voting/templates/voting/signup.html
{% extends 'voting/main.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
   
    <div class="row image">
        <div class="col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
            <form method="post" style="margin-top: 15%; margin-left: 60%; margin-right:-43%; margin-bottom: 10%">
                <div class="form-control form-control">
                    <div class=""  style="margin-left: 3%">
                        <div class="row">
                            <div class="">
                                <h1 class="fg-site"><b>Signup now to start Voting</b></h1><hr>
                                {% csrf_token %}
                                {% for field in form %}
                                  <p>
                                    {{ field.label_tag }}<span style="color: red">*</span>
                                    {{ field }}<br>
                                    {% for error in field.errors %}
                                      <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                  </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1 clearfix">
                                <button class="btn btn-secondary pull-right" type="submit"><b>Signup</b></button><br>
                                Already have an account?
                                <a href="{% url 'login' %}"><b>Login</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
{% endblock %}

voting/templates/voting/signup1.html
{% extends 'voting/main.html' %}

{% block title %}About  Panther Es{% endblock %}

{% block content %}
Signup
{% endblock %}

voting/templates/voting/update_profile.html
{% extends 'siteLayout.html' %}

{% block title %}Edit your profile information{% endblock %}

{% block content %}
    <br />
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
            <form method="post">
                <div class="panel panel-site" style="border-top: none; border-right: none">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                {% if msgInfo %}
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                      {{ msgInfo }}
                                    </div>
                                {% endif %}
                                <h1 class="fg-site"><b>Edit your profile information</b></h1>
                                {% csrf_token %}
                                {% for field in form %}
                                  <p>
                                    {{ field.label_tag }}<br>
                                    {{ field }}
                                    {% if field.help_text %}
                                      <small style="color: grey">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                      <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                  </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1 clearfix">
                                <button class="btn btn-site pull-right" type="submit"><b>Save changes</b></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}