authusers/urls.py
from django.urls import path

from . import views

app_name = "authusers"
urlpatterns = [
    path('home', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('elections', views.elections, name='elections'),
    path('election/<id>', views.election, name='election'),
    path('vote/<id>', views.vote, name='vote'),
    path('results', views.results, name='results'),
    path('result<id>', views.result, name='result'),
    path('upload/<id>', views.upload, name = 'upload'),
]

election/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import views as auth_views
from voting import views as reg_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("voting.urls")),
    path('', include("authusers.urls")),
    path('login/', auth_views.login, {'template_name': 'voting/login.html'}, name='login'),
    path('logout/', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^signup/$', reg_views.signup, name='signup'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^account_activation_sent/$', reg_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        reg_views.activate, name='activate'),
    # password change url definitions
    url(r'^accounts/password/change/$', auth_views.password_change, {
        'template_name': 'registration/password_change_form.html'},
        name='password_change'),
    url(r'^accounts/password/change/done/$', auth_views.password_change_done,
        {'template_name': 'registration/password_change_done.html'},
        name='password_change_done'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "users"
urlpatterns = [
    path('home', views.home, name='home'),
    path('dashboard', views.home, name='dashboard'),
 ]

authusers/models.py
from django.db import models

# Create your models here.

authusers/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from voting.models import Elections, Position, Candidate,Voting
from django.core.files.storage import FileSystemStorage
import os.path

def home(request):
	context_object_name = 'Elections'
	
		#Return all elections ordered by dateAdded
	elections = Elections.objects.all();
	return render(request, 'authusers/home.html', {'elections':elections})
    #return HttpResponse("Hello, world. You're at the polls index.")
    
def dashboard(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'authusers/home.html')

def elections(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'authusers/home.html')

def election(request, id = 0):
    #get the election
    election = Elections.objects.get(pk= id)
    # get the various post assoicated with the elections.
    posts = Position.objects.filter(election_id = id)
    #get all the candidates for the election
    candidates = Candidate.objects.filter(election_id = id)
    votes = Voting.objects.filter(election_id = id)
    return render(request, 'authusers/election.html', { 'election': election, 'posts':posts, 'candidates':candidates, 'votes':votes})

#This function is to register the vote
def vote(request, id = 0):

	#get the candidate voted for
	candidate = Candidate.objects.get(pk = id)
	#Get all your voted candidates for that election
	elecs =  Voting.objects.filter(election_id = candidate.election_id, user_id = request.user.id)
	#get the position
	for elec in elecs:
		candi  = Candidate.objects.get(pk = elec.candidate_id) 
		if candi.position_id == candidate.position_id:
			elec.candidate_id = id
			elec.save()
			return election(request, id = candidate.election_id )
		
	#register the vote
	vote = Voting.objects.create(candidate_id = id, user_id = request.user.id, election_id = candidate.election_id)
	vote.save()
	return election(request, id = candidate.election_id )
	#call the election view

	return HttpResponse("Hello, world. You're at the polls index.")

#show all the elections to be selected
def results(request):
	#Return all elections ordered by dateAdded
	elections = Elections.objects.all();
	return render(request, 'authusers/results.html', {'elections':elections})

def result(request, id):
	election = Elections.objects.get(pk= id)
	#get all the votes of the election
	allvotes = Voting.objects.filter(election_id = id)
	#get all the candidates for the election
	candidates = Candidate.objects.filter(election_id = id)
	#get all the post
	posts = Position.objects.filter(election_id = id)
	return render(request, 'authusers/result.html', {'allvotes':allvotes, 'posts':posts, 'candidates':candidates, 'election':election})

#To Upload the users Profile Picture
def upload(request, id):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage('static/images')
        ouruser = request.user
        iden = str(ouruser.id)
        fileexist = FileSystemStorage('static/images/'+ iden)
        if os.path.exists('static/images/'+ iden):
        	 os.remove('static/images/'+ iden)
        filename = fs.save(str(ouruser.id), myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'authusers/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'authusers/simple_upload.html')

#to upload the pictures and save some data
def formupload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'core/model_form_upload.html', {
        'form': form
    })

authusers/templates/authusers/base.html
{% extends 'authusers/main.html' %}
    {% block content %}
    {% endblock %}

authusers/templates/authusers/election.html
{% extends 'authusers/main.html' %}

{% block title %}About  Panther Es{% endblock %}

{% load static %}	
{% block content %}
	<ul>
		<h3>Election Details</h3>
		<table class="table table-stripped text-secondary">
			<thead>
				<tr>
					<th>Name</th>
					<th>Voters Type</th>
					<th> Electors Type </th>
				</tr>
			</thead>
			<tbody>
					<tr>
						<td>
							{{ election.name }}
						</td>
						<td>
							{{ election.voterType }}
						</td>
						<td>
							{{ election.electorType }}
						</td>
					</tr>
			</tbody>
		</table>
	</ul>
	<div class="container">
		<table class="table table-stripped text-secondary">
			<thead>
				<tr>
					<th>Post</th>
					<th>Candidates</th>
				</tr>
			</thead>
			<tbody>
				{%  if posts %}
					{% for post in posts %}
					<tr>
						<td>
							{{ post.name }}
						</td>
						<td>

							{% if candidates %}
								<table class="table table-stripped">
										<div class="row">
										{% for candidate in candidates %}

												{% if post.idPosition == candidate.position_id %}
													<div class="col-md-3 ">
														<div class="card">
															<div class="card-header">
																<h4 class="card-title">{{ candidate.user }}</h4>
  																<a href="{% url 'authusers:vote' candidate.idCandidate %}" class="card-link text-danger"><span class=" glyphicon glyphicon-heart" aria-hidden="true">Vote 💚</span></a>
															</div>
  															<div class="card-body">
  																<img class="card-img-top" src="{% static 'images/'%}{{ candidate.userid_id }}"  alt="Profile pic" style="width:100%">
  															</div>
  															{% if votes %}
  															<div class="card-footer">
  																
																	{% for vote in votes %}
																		{% if vote.candidate_id == candidate.idCandidate %}
																		{% if user.id == vote.user_id%}
																				<div class="text-info">You Voted {{ candidate.user }}</div>
																			
																		{% endif %}
																		{% endif %}	
																	{% endfor %}
  															</div>
  															{% endif %}
  														</div>
													</div>
												{% endif %}
										{% endfor %}
									</div>
								</table>
							{% else %}
								There are no Candidates yet for this Elections
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				{% else %}
					<tr>
						There are no positions yet for the election
					</tr>
				
				{% endif %}
			</tbody>
		</table>
	</div>
{% endblock content %}

authusers/templates/authusers/home.html
{% extends 'authusers/main.html' %}

{% block title %}About  Panther Es{% endblock %}
{% load static %}

{% block content %}
	
{% if user.is_authenticated %}
	<style type="text/css">
		.card {
		    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
		    transition: 0.3s;
		    width: 40%;
		    border-radius: 5px;
		    background-color: #eeeeee;
	}

		.card:hover {
		    box-shadow: 4 16px 32px 0 rgba(0,0,0,0.2);
		}
	</style>
	<div>
	<div class="row" style=" margin: 50px">
		<div class="card Card col-md-4">
			<img class="card-img-top" src="{% static 'images/'%}{{ user.id }}"  alt="Profile pic" style="width:100%">
			<a href="{% url 'authusers:upload' user.id %}" class="card-link btn btn-secondary">Change Your DP</a>
		</div>
		<div class="col-md-8">
			<h3 class="text-center text-secondary">
			<p>{{ user.get_username }}, we need your vote 😃</p>
				{% else %}
					<p>Hello! Welcome, Please log in.</p>
				{% endif %}
		
		</h3><br>
		</div>
	</div>
	

<div class="container">
	<div class="row">
		{% if elections %}		
			{%  for election in elections %}			
				<div class="card Card col-md-4">
				  <div class="card-header">
				  	<img class="card-img-top" src="http://www.personal.kent.edu/~lzucca/j0433151.jpg" style="width:100%">
				  </div>
				  <div class="card-body">
				    <h4 class="card-title">{{ election.name }}</h4><hr>
				    <p class="card-text">Some example text. Some example text.</p><p>Voters type: {{ election.voterType }}<br>Elector Type: {{ election.electorType }}</p>
				    <a href="{% url 'authusers:election' election.idElection %}" class="card-link btn btn-secondary">Select</a>
				    <a href="#" class="card-link btn btn-info">More info</a>
				  </div>
				</div>								
	   		{% endfor %}	
	   	{% else %}
	   		No Elections Yet
		{% endif %}    
	</div><br><br>
	<div class="row form-group" style="margin-left: 33%;"><span>Email: </span><input class=" off-set-md-2 form-control col-md-5" type="email" name="email" placeholder="Please subcribe to our news"><input type="Submit" name="subscribe" class="btn btn-info"></div>
</div><br><br>
{% endblock %}

authusers/templates/authusers/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Panther - Electoral System{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/site.css' %}">
        
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
         <style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width: 100%;
      height: 100%;
  }
  </style>
    </head> rel="stylesheet" href="{% static 'css/site.css' %}">
    </head>
      <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand" href="#">Panther - Electoral System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authusers:home' %}"><span>Home</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'authusers:elections' %}"><span></span> Elections</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'authusers:results' %}"><span></span> Results</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

         <div>
              {% block content %}Empty page!{% endblock content %}
          </div>

          
      </body>
      <br><br><br>
          <footer class="footer bg-dark" style="position: relative;">
            <div class="container-fluid">
              <span class="text-basic">Powered by Mondjo Perside & Nges Brian</span></div>
          </footer>
       
</html>

authusers/templates/authusers/result.html
{% extends 'authusers/main.html' %}

{% block title %}About  Panther Es{% endblock %}

{% block content %}
	<ul>
		<h3>Election Details</h3>
		<table class="table table-stripped text-secondary">
			<thead>
				<tr>
					<th>Name</th>
					<th>Voters Type</th>
					<th> Electors Type </th>
				</tr>
			</thead>
			<tbody>
					<tr>
						<td>
							{{ election.name }}
						</td>
						<td>
							{{ election.voterType }}
						</td>
						<td>
							{{ election.electorType }}
						</td>
					</tr>
			</tbody>
		</table>
	</ul>
<div class="container">
		<table class="table table-stripped text-secondary">
			<thead>
				<tr>
					<th>Post</th>
					<th>Candidates</th>
				</tr>
			</thead>
			<tbody>
				{%  if posts %}
					{% for post in posts %}
					<tr>
						<td>
							{{ post.name }}
						</td>
						<td>

							{% if candidates %}
								<table class="table table-stripped">
									<thead>
										<tr>
											<th>Name</th>
											<th> No Vote </th>
										</tr>
									</thead>
									<tbody>
										{% for candidate in candidates %}
											<tr>
												{% if post.idPosition == candidate.position_id %}
													<td>
														{{ candidate.user }}
													</td>
													<td>
														{% load showVotes %}
															{% showVotes %}
																{% include 'authusers/showVotes.html'%}
															{% showVotes%}
													</td>
												{% endif %}
											</tr>
										{% endfor %}
									</tbody>
								</table>
							{% else %}
								There are no Candidates yet for this Elections
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				{% else %}
					<tr>
						There are no positions yet for the election
					</tr>
				
				{% endif %}
			</tbody>
		</table>
	</div>
{% endblock content %}

authusers/templates/authusers/results.html
{% extends 'authusers/main.html' %}

{% block title %}About  Panther Es{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% if user.is_authenticated %}
			   <h3>
				    <p>Welcome, {{ user.get_username }}. to Panther ES.</p>
					{% else %}
					    <p>Welcome, to Panther. Please log in to vote.</p>
					{% endif %}
				</h3>
		</div>
	</div>
	<ul class="text-secondary">
		{% if elections %}
			Here are the Different Elections Avalible
			<table class="table table-stripped">
				<thead>
					<tr class="text-info">
						<th>Name</th>
						<th>Voters Type</th>
						<th> Electors Type </th>
						<th>Select </th>
					</tr>
				</thead>
				<tbody>
					{%  for election in elections %}
						<tr>
							<td>
								{{ election.name }}
							</td>
							<td>
								{{ election.voterType }}
							</td>
							<td>
								{{ election.electorType }}
							</td>
							<td><a class="text-danger" href="{% url 'authusers:result' election.idElection %}"><span class="glyphicon glyphicon-ok"></span> Select</a></td>
						</tr>
   					{% endfor %}
				</tbody>
			</table>
			
   		{% else %}
   			Sorry! No Elections Yet
		{% endif %}
    
</ul>
{% endblock %}

authusers/templates/authusers/showVotes.html
{% if num_votes %}
	<div class="text-info">{{ num_votes }}</div>
{% else %}
	<div class="text-danger">0</div>
{% endif %}

authusers/templates/authusers/simple_upload.html
{% extends 'authusers/base.html' %}

{% block title  %} Change Image{% endblock %}

{% load static %}

{% block content %}
<div style="margin-left: 10% !important; margin: 25%" class="text-center">
	 <form method="post" enctype="multipart/form-data">
	    {% csrf_token %}
	    <input type="file" name="myfile">
	    <button type="submit">Upload</button>
	  </form>

	  {% if uploaded_file_url %}
	    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
	  {% endif %}

	  <p><a href="{% url 'authusers:dashboard' %}">Return to home</a></p>
	{% endblock %}
</div>
 